### ISSUE TITLE
Add type information

### ISSUE THREAD

**Issue by ssured** [laggingreflex/file-watch-iterator#1]
Async iterators make sense here, thanks for sharing

I made some (incomplete) typescript typings, maybe you are interested in adding these, otherwise others can find them in this issue.

```typescript
declare module 'file-watch-iterator' {
    import { WatchOptions } from 'chokidar';

    export type Files = {
        files: Record<string, { changed: boolean; event: 'add' | 'changed' | 'unlink' }>;
    };

    export default function watch(
        path: string,
        options?: WatchOptions,
        watchOptions?: { debounce: number },
    ): AsyncIterableIterator<Files>;
}
```

**Comment by laggingreflex** [comment]
I'd very much welcome a PR.

I don't have enough TypeScript experience to implement this myself. 

I personally prefer JSDoc-style typings that VSCode is able to lift easily. I tried to to write them but being a complex AsyncIterator that uses yet [another module](https://github.com/laggingreflex/break-async-iterator) as a wrapper makes it a bit difficult. I'll see if I can manage to write them that way (my initial attempt (#2) didn't work).

**Comment by ssured** [comment]
Cool you added the jsdoc. It's the better approach as this is a js library. I have no experience with jsdoc typings. If you want to try and build a TS library, I can really recommend https://github.com/jaredpalmer/tsdx which has all boilerplate done and publishes plain JS alongside TS. Thanks!
